### PR TITLE
Dockerfile: rework to match current project status

### PR DESCRIPTION
**Pull request by Strubbl**
* update to python 3.8
* update npm to v14
* add Debian package `libsecret-1-dev` as dependency for joplin
* deploy application according to current instructions from README
* update `docker-start.sh` to match current project structure

### CODE REVIEW

**Comment by foxmask** [comment]
when running `docker build -t joplin-web-build .` ; the build finished by 
```
Step 8/9 : COPY .env /app/joplin-web/joplin-web/joplin_web/
COPY failed: stat /var/lib/docker/tmp/docker-builder239928449/.env: no such file or directory
```
:/

**Comment by foxmask** [comment]
i'm also asking myself, how the JOPLIN_WEBCLIPPER_TOKEN (in the .env file) can be filled with the Dockerfile
In the current version, once the `.env` file is copied, the var is empty, and requesting to joplin will failed

**Comment by Strubbl** [comment]
Yes, you need to provide a valid `.env` file along with the Dockerfile you are compiling. Currently i have no better solution.

> In the current version, once the `.env` file is copied, the var is empty, and requesting to joplin will failed

I do not get this. Why is the variable empty in the container? Do you get any error message? 
The joplin_web app.py should find the env file with the token in it in the same path as the app.py is placed.

**Comment by foxmask** [comment]
the .env file is coming from the git clone just before the copy? I'll retry.

**Comment by Strubbl** [comment]
No you need to create the .env file manually. E.g. you have the local copy of this git repository on your disk. in that folder, where the Dockerfile is also in, you need a valid .env file which has your JOPLIN_WEBCLIPPER_TOKEN etc. Then, you can `docker build` and while that your .env file is going to be copied into the container.

**Comment by foxmask** [comment]
the .env file is in joplin_web folder, so I put in the docker file
```
COPY joplin_web/.env /app/joplin-web/joplin-web/joplin_web/
```
and then the build is ok

I tried to start docker
```
08:36 $  docker run -p 8001:8001 -v /data/joplin-desktop:/data -e JW_FULL_URL="http://127.0.0.1:8001/" joplin-web-build
joplin-web available at http://127.0.0.1:8001/
sed: can't read /app/templates/index.html: No such file or directory
```
I don't see where a `sed` is trying to replace a content into  /app/templates/index.html.

the path "/app/templates/index.html" was in my own docker-start.sh but as I merge yours, the docker run command should not find that path in the docker-start.sh script o_O

**Comment by foxmask** [comment]
Ha, I know... the docker-script.sh file that is running is the one that is pulled from my git repo and not from yours:) 
and as the docker-scripts.sh does not yet contain your fixes :)) 
I try some stuff to see

**Comment by foxmask** [comment]
found a solution to make a test :)

**Comment by foxmask** [comment]
thanks for the PR

**Comment by Strubbl** [comment]
> Ha, I know... the docker-script.sh file that is running is the one that is pulled from my git repo and not from yours:)

Yes, you are right. that's very tricky. Thanks for testing & the merge

**Pull request merged**
